<div style="text-align: center;">
<font style="font-size: 65px; color: darkblue;"> Welcome! </font>
<br>
<font style="font-size: 50px; color: darkblue;"> Titanic - Machine Learning from Disaster </font>
</div>

******
This project was developed by:

* Afonso Coelho ([Bugss05](https://github.com/Bugss05)) - FCUP_IACD: 202305085
* Diogo Amaral ([damaral31](https://github.com/damaral31)) - FCUP_IACD: 202305187
* Miguel Carvalho ([miguel-c05](https://github.com/miguel-c05)) - FCUP_IACD: 202305229



Table of contents  
blablalallalvlv



## <font style="font-size: 45px; color: darkblue;"> 1 Introduction </font>

### <font style="font-size: 25px; color: blue;"> 1.1 Problem context </font>

&nbsp;&nbsp; This notebook serves as the workspace for the Kaggle competition ["Titanic - Machine Learning from Disaster"](https://www.kaggle.com/competitions/titanic), a Machine Learning exercise best suited for beginners, especially those new to the  [kaggle](<https://www.kaggle.com>) platform.
<br>
&nbsp;&nbsp; The aim of the competition at hand is to ``study a Database of passengers aboard the Titanic`` and train a ``Machine Learning model`` on any relevant information extracted in order to be able to predict whether a passenger is likely to survive the ship's wreck or not. All of this with the maximum accuracy possible, of course.

<div>
    <div style="width: 50%;float: left ">

### <font style="font-size: 25px; color: blue;"> 1.2 Expectations </font>
&nbsp;&nbsp; On a first inspection of the facts, ``women and children will most likely have a higher chance of survival``, simply because they were groups of people prioritized for evacuation and rescue. Some cabins may also see a survivability increase solely due to its geographical location on the ship as seen on the following image (Img 1).

## <font style="font-size: 45px; color: darkblue;"> 2 The Data </font>
 &nbsp;&nbsp;In order to train the model a large enough amount of information is needed. As such, Kaggle gives the participants of this competition a dataset (``train.csv``) on which to work, regarding passenger's`` names, age, sex and nÂº of siblings, among others``. <br>
 
 It also contains, however, ``missing values as well as outliers``, both of which harm data analysis and model training. Later, we will explain how such cases were handled.

</div>

<div style="width: 35%; float: left; padding-left: 10% ">
    <figure style="float: left; height: 100%; width: 100%;">
          <img src="Titanic_cutaway_diagram.png" style="height: 600px; width: 100%;">
          <figcaption style="text-align: center;">Img 1: Titanic cutaway diagram. Normaly the lower classes passagers were placed lower in the ship </figcaption>
        </figure>
</div>
</div>

### <font style="font-size: 25px; color: blue;"> 2.1 Data Sample </font>
This dataset has roughly ``900 passengers and 10 features and 1 output class``.
*  ``survived`` - 1 if lived 0 if not (output class)
* ``Name`` - Name 
* ``pclass`` - ticket class 1-1st, 2-2nd, 3-3rd
* ``sex`` - Male or female
* ``Age ``- Age in years 
* ``sibsp`` - # of siblings / spouses aboard the Titanic	
* ``parch`` - # of parents / children aboard the Titanic	
* ``ticket``- Ticket number 
* ``fare``- Passenger fare
* ``cabin``- Cabin Number
* ``embarqued`` - Port of Embarkation	C = Cherbourg, Q = Queenstown, S = Southampton

If interested in how the raw data was offered run the next code to visualize it.

In [ ]:
import pandas as pd
import numpy as np

data= pd.read_csv('train.csv')
display(data)

### <font style="font-size: 25px; color: blue;">2.2 added\excluded features  </font>
&nbsp;&nbsp;We took in consideration some aspects such as ``missing values and relevance`` for the output class.<br>

>&nbsp;&nbsp;At first glance, the ``"name" feature`` seems pretty useless however, the ``last name`` can connect families since they are most likely to stay together in the ships wreck.<br>
>&nbsp;&nbsp;The same case applies to the ``"ticket" atribute`` since there's no specific explanation on what the numbers and letters represents, yet the same ticket can too relate to the same family or some friends that stayed on the same cabin.

>&nbsp;&nbsp; We also decided to remove any feature with ``>50% of missing values ``.

>&nbsp;&nbsp; As this event a large amount of passengers died, we though that the missing value for a passenger can be related for them to be dead so for any atriute that`` has missing values we added a binary column such that 0 if the value is not missing and 1 if the value is missing.``.   
         
### <font style="font-size: 25px; color: blue;">2.3 Missing values </font>
#### <font style="font-size: 20px; color: lightblue;">2.3.1 Missing values info</font>
Heres some plot of each percentage of missing values

In [6]:
def missing_values(df: pd.DataFrame) -> None:
    """
    por cada coluna do dataset deve ser calculado o nr de missing values a percentagem de missing values.
    este deve ser o formato de do novo ficheiro csv:

    |  Column  | Missing Values |  Percentage |
    |----------|----------------|-------------|
    | Column 1 |       0        |      0      |
    | Column 2 |       2        |     0.2     |
    |   ...    |      ...       |     ...     |

    o nome do ficheiro TEM DE SER "missing_values.csv"
    """
    lista_valores_percentagem = []
    for col in df.columns:
        lista_valores_percentagem.append([col, df[col].isnull().sum(), df[col].isnull().sum() / len(df[col])])
    df_missing_values = pd.DataFrame(lista_valores_percentagem, columns=['Column', 'Missing Values', 'Percentage'])
    df_missing_values.to_csv('missing_values.csv', index=False)
    
data = pd.DataFrame(pd.read_csv('train.csv'))
missing_values(data)
print("Missing values train: ")
display(pd.read_csv('missing_values.csv'))
data = pd.DataFrame(pd.read_csv('test.csv'))
missing_values(data)
print("Missing values test: ")
display(pd.read_csv('missing_values.csv'))

Missing values train:

         Column  Missing Values  Percentage
0   PassengerId               0    0.000000
1      Survived               0    0.000000
2        Pclass               0    0.000000
3          Name               0    0.000000
4           Sex               0    0.000000
5           Age             177    0.198653
6         SibSp               0    0.000000
7         Parch               0    0.000000
8        Ticket               0    0.000000
9          Fare               0    0.000000
10        Cabin             687    0.771044
11     Embarked               2    0.002245

Missing values test:

         Column  Missing Values  Percentage
0   PassengerId               0    0.000000
1        Pclass               0    0.000000
2          Name               0    0.000000
3           Sex               0    0.000000
4           Age              86    0.205742
5         SibSp               0    0.000000
6         Parch               0    0.000000
7        Ticket               0    0.000000
8          Fare               1    0.002392
9         Cabin             327    0.782297
10     Embarked               0    0.000000